name: 'Manage Users Action'
description: 'Run this action to provide access to users for certain teams in an organization'
author: 'githubpartners-community'
inputs:
  users:
    required: true
    description: 'GitHub slug of users to provide access to'
  action:
    required: true
    description: 'Action to be performed: add or remove'
  token:
    required: true
    description: 'Personal Access Token or GITHUB_TOKEN (or comma separated tokens)'
  teams:
    required: true
    description: 'Comma-separated slugs of the teams to add users to'
  organization:
    required: true
    description: 'GitHub organization name'
runs:
  using: 'node16'
  main: 'dist/index.js'
